### ISSUE TITLE
Is vault thread-safe?

### ISSUE THREAD

**Issue by andrewthad** [HeinrichApfelmus/vault#20]
I don't see this addressed anywhere in the docs, and I assume that it isn't thread-safe, but I just wanted to check.

**Comment by HeinrichApfelmus** [comment]
If you're using GHC, the library is thread-safe, because it uses only pure data structures (and `unsafecoerce`…). If you're using another compiler, then probably not.

**Comment by andrewthad** [comment]
Thanks! I had forgotten that it didn't run in IO. Too much STM lately.
