### ISSUE TITLE
Allow GHC 8.0

### ISSUE THREAD

**Issue by ndmitchell** [HeinrichApfelmus/vault#23]
GHC 8.0 ships with base-4.9, which is disallowed by vault. A new release which can be used with GHC would be useful, and would allow me to test my downstream projects with GHC 8.0.

**Comment by HeinrichApfelmus** [comment]
Done. I've update the .travis.yml configuration and released version `vault-0.3.0.6` on hackage. Thanks!

**Comment by ndmitchell** [comment]
Thanks a lot, most appreciated :)
