### ISSUE TITLE
release a new version on hackage (or make a hackage revision) to support hashable-1.3.0.0

### ISSUE THREAD

**Issue by int-e** [HeinrichApfelmus/vault#28]
There is a new major release of [hashable](https://hackage.haskell.org/package/hashable-1.3.0.0). As far as I can see, bumping the upper bound is enough to support it.

Interestingly, this is actually causing problems at the moment (`cabal-install` is having a hard time finding installation plans, e.g. https://github.com/lambdabot/lambdabot/issues/183).

**Comment by int-e** [comment]
ping?

**Comment by kazu-yamamoto** [comment]
ping

**Comment by int-e** [comment]
I've raised this with the hackage trustees here: https://github.com/haskell-infra/hackage-trustees/issues/230

**Comment by int-e** [comment]
ping?

There really isn't much to do here; just bumping the upper bound through a hackage revision will do the trick. The reasons for the major version bump in hashable are unrelated to vault's usage (vault defines its own `Hashable` instance for its `Unique` type): The instances for `Arg` and the floating point numbers have been changed to align with the corresponding `Eq` instances.

**Comment by kazu-yamamoto** [comment]
Ping from me, too.

**Comment by dminuoso** [comment]
@HeinrichApfelmus Seeing as you have already made the change in 4f9f0dcf0f8491a3fb6f406439c42e219dbacc71 - would you mind uploading a new version to fix this issue?

**Comment by kazu-yamamoto** [comment]
@int-e We can close this.

**Comment by int-e** [comment]
@kazu-yamamoto: I've changed the description to be more accurate.

**Comment by kazu-yamamoto** [comment]
Oh. New versions do not support hashable 1.3. Sigh.

**Comment by HeinrichApfelmus** [comment]
I'm sorry for the long delay. I have uploaded [v0.3.1.3](https://github.com/HeinrichApfelmus/vault/releases/tag/v0.3.1.3). Does that fix the issue?

**Comment by int-e** [comment]
Thanks! That fixes the issue for lambdabot at least.
