### ISSUE TITLE
Travis integration is broken

### ISSUE THREAD

**Issue by sjakobi** [HeinrichApfelmus/vault#31]
For example, in https://github.com/HeinrichApfelmus/vault/pull/30, there is no indication whether the Travis build succeeded or not.

I have already experienced this in several other repos, and it has already caused me quite a bit of pain.

@HeinrichApfelmus, since you're the admin of this repo, I think only you can fix this. Could you try following the instructions that I posted in https://github.com/quchen/prettyprinter/issues/172#issuecomment-653885208?

**Comment by HeinrichApfelmus** [comment]
I have clicked many buttons and prayed to the half-filled electron sea. Did it work? Something does seem to be happening:

  https://travis-ci.com/github/HeinrichApfelmus/vault/jobs/367144882

**Comment by sjakobi** [comment]
@HeinrichApfelmus Yes! :)

See https://github.com/HeinrichApfelmus/vault/pull/32

Your prayers have been heard. The electronic gods smile upon you.
