### ISSUE TITLE
GHC 9.10 compat

### ISSUE THREAD

**Issue by ysangkok** [HeinrichApfelmus/vault#42]
The package v0.3.1.5 excludes base-4.20, which is the version that ghc9.10 uses according to [release notes](https://downloads.haskell.org/ghc/9.10.1/docs/users_guide/9.10.1-notes.html#included-libraries)

**Comment by ocramz** [comment]
Can confirm, we just ran into this in `scotty` CI : https://github.com/scotty-web/scotty/actions/runs/9045369840/job/25086392372?pr=399#step:6:14 

Please increase the upper bound on base
