### ISSUE TITLE
hashable-1.5 not accepted

### ISSUE THREAD

**Issue by ysangkok** [HeinrichApfelmus/vault#44]
v0.3.1.5 of vault, on Hackage, doesn't accept this version of hashable. Would be nice to support it.

**Comment by kazu-yamamoto** [comment]
@HeinrichApfelmus Gentle ping.

**Comment by HeinrichApfelmus** [comment]
@kazu-yamamoto Thanks for the ping, things tend to get lost in my Github notifications page.

I used to get pings on version upgrades for dependencies from https://packdeps.haskellers.com , but that service is no longer operational, unfortunately.

**Comment by HeinrichApfelmus** [comment]
I have updated and tested dependencies in #45 . I have published a new revision on Hackage.

Please feel free to reopen if that doesn't solve your issue.

**Comment by ysangkok** [comment]
@HeinrichApfelmus Since you mentioned packdeps, you might like to know that you can now get dependency notifications directly from Hackage, but you have to [opt in](https://discourse.haskell.org/t/hackage-dep-bound-notifications-and-uploader-endorsements-for-new-users/8342?u=janus).

**Comment by kazu-yamamoto** [comment]
Thank you!
